Refactor bot
aleksander-git/telegram-torrent pull request #22
Opened 2024-08-15 15:16 UTC by dadilll

2024-08-15 16:38 UTC, LLIEPJIOK requested changes
В дополнение ещё глянь `internal/appllication/bot/bot.go`. Там стоит `package main`, что вызывает конфликты с `cmd/bot/main.go`, надо подправить на `package bot`.

Файл `internal/database/torrent.go` можно удалить, он уже не используется

2024-08-15 16:38 UTC, LLIEPJIOK commented on internal/database/backend/connectingdb.go
> +	Queries *Queries
Почему убрал встраивание? Как по мне это было более элегантное решение, так как не надо было бы писать методы, которые будут вызывать методы **Queries**.

Поле **db**, наверное, и не нужно, оно же используется только для создания **Queries**

2024-08-15 16:38 UTC, LLIEPJIOK commented on internal/database/backend/connectingdb.go
>  		db:      db,
**sql.Open** не достаточно для установления соединения с базой данный, надо ещё использовать **db.Ping**. Про это можешь прочитать [тут](https://pkg.go.dev/database/sql#Open). 
Возможно стоит предусмотреть закрытие соединения и обработку ошибки перед завершением приложения. В целом соединения закрываются сами, но в таком случае мы не сможем узнать, произошла ли там ошибка

2024-08-15 16:38 UTC, LLIEPJIOK commented on internal/database/backend/connectingdb.go
> -	_ "github.com/lib/pq"
Почему убрал библиотеку? Она же подгружает драйвер, который нужен для работы с Postres

2024-08-15 16:57 UTC, dadilll commented on internal/database/backend/connectingdb.go
> +	Queries *Queries
Я посчитал что будет лучше отказаться от встраивания, так как это улучшает тестируемость и поддерживаемость кода в будущем.

2024-08-15 17:54 UTC, LLIEPJIOK commented on internal/database/backend/connectingdb.go
> +	Queries *Queries
Я не вижу каких-то особых проблем с тестированием. Поддерживаемость тоже спорная. С одной стороны это действительно увеличивает читаемость кода. С другой же, если будут добавляться/удаляться запросы, то придётся вручную их добавлять/удалять тут. Возможно это вкусовщина

Если хочешь оставить так, то посмотри методы:
- `GetTorrents`: там должен быть айди пользователя, для которого надо получить торренты, ты почему-то всегда 0 отправляешь
- `GetSetting`: туда должны передаваться имя настройки и айди пользователя, сейчас туда передаётся только имя настройки, но и оно дальше не используется

2024-08-16 07:08 UTC, dadilll commented on internal/database/backend/connectingdb.go
> +	Queries *Queries
исправил

2024-08-19 14:18 UTC, LLIEPJIOK approved these changes

2024-08-22 10:10 UTC, aleksander-git commented on internal/bot/command.go
> +			b.logger.Error(fmt.Sprintf("b.handleAddingNewTorrent(%q, %d, %q): %s", userName, chatID, link, err))
Описание ошибки не соответствует

2024-08-23 08:20 UTC, merged